import { preParse } from "@/app/functions/text";

export default function AboutPage() {
    return (
        <div className="max-w-[1000px] mx-auto p-4 pb-10 flex flex-col gap-2">
            <h1 className="font-bold text-xl">What is Reccs?</h1>
            <p>{preParse("Reccs is an archive of collections of literary, cinematic, theatrical, and analytical achievements from each of the United Nations geoscheme subregions (modified slightly to better conform the subregions, devised for statistical purposes, to their corresponding culturally-affiliated regions).")}</p>
            <p>{preParse("These selections are limited to works that have been translated into English, a considerable bottleneck (like the act of translation—and writing, for that matter—itself) in capturing the full extent of human literary output, but at the same time a noteworthy asset in allowing some degree of access to a plurality of worldviews for the extensive native and non-native English-speaking populations of the world (at present the most prevalent of all speech communities). For every selection, I include a brief description of the work or genre, sources for further reading, and other relevant media, such as text excerpts, playlists, or related videos.")}</p>
            <h1 className="font-bold text-xl mt-4">About the Geoscheme</h1>
            <p>{preParse("Taking the UN geoscheme subregions as starting point, the following two principles account for the range of modifications made to finalize the list of regions I’ve compiled: (1) de-emphasize colonial populations (even when they’re demographically or politically dominant) that do little to represent the local historical developments associated with a particular landscape (e.g. Germanic colonial holdings (U.S., Australia, New Zealand, South Africa, Indonesia); Latin colonial holdings (Criollo/Mestizo Latin America, the Phillippines); Bantu expansion areas (Khoisan territory, Madagascar); peripheries of Arabization (Maghreb, Horn of Africa)) and (2) by extension, where the UN declines to separate countries, break up imperial nation-states into sufficiently distinct cultural regions by depth of historical ties (e.g. Slavic colonial holdings (Siberia); frontier Indian administrative divisions (Sikkim, Ladakh, Arunachal Pradesh); frontier Chinese administrative divisions (Tibet, Xinjiang); arbitrary North American (Canada, U.S., Mexico) and South American (Peru, Brazil, Argentina) state boundaries). To put it simply, these principles prioritize (1) autochthony (i.e. being from a place) and its facilitating (2) counter-expansionism (i.e. limiting the maximum extent of that place) as principles providing a higher-fidelity gage for establishing a connection between human cultural innovations and their geography of origin—in a way that the United Nations, which represents the governments of the (self-fulfilling) internationally agreed upon nations of the contemporary world, is understandably incapable of reflecting in its geoscheme.")}</p>
            <p>{preParse("We're trying to present a way of understanding the world somewhere between the geographic features of its land masses (e.g. Great Britain, New Guinea, the central Eurasian Steppe) and the contemporary human political divisons superimposed thereon (e.g. United Kingdom, Papua New Guinea, Kazakhstan), elevating the ways in which the two interact, through migration and cohabitation, in the honest light of history to create the complete variety of distinct human cultural regions.")}</p>
        </div>
    )
}