import { Syncopate, Noto_Sans, Noto_Sans_Malayalam, Noto_Serif_Tibetan, Noto_Sans_Canadian_Aboriginal, Noto_Sans_Arabic, Noto_Sans_Tamil, Noto_Sans_Telugu } from 'next/font/google';
import localFont from 'next/font/local';

export const syncopate = Syncopate({ weight: ['400','700'], subsets: ['latin'] });
export const notoSans = Noto_Sans({ weight: ['300','400','500','600','700','800'], subsets: ['latin'] });
// Conditional script fonts. Exposed as CSS variables (not `.className`) and applied
// once on <html> in layout.tsx, so the @font-face + variable are defined a single time
// in the server-rendered layout. checkFont() then returns stable utility classes
// (globals.css) that read these variables — no next/font hash ever crosses the
// server/client boundary, which is what caused the SSR class to ship without CSS.
// `preload: false`: these are per-entry scripts, so the woff2 downloads only when a
// matching glyph is actually rendered rather than preloading all six on every page.
export const notoMalayalam = Noto_Sans_Malayalam({ weight: ['400','500','600','700','800','900'], subsets: ['malayalam'], variable: '--font-noto-malayalam', preload: false });
export const notoTibetan = Noto_Serif_Tibetan({ weight: ['400','500','600','700','800','900'], subsets: ['tibetan'], variable: '--font-noto-tibetan', preload: false });
export const notoCanadian = Noto_Sans_Canadian_Aboriginal({ weight: ['400','500','600','700','800','900'], subsets: ['canadian-aboriginal'], variable: '--font-noto-canadian', preload: false });
export const notoArabic = Noto_Sans_Arabic({ weight: ['400','500','600','700','800','900'], subsets: ['arabic'], variable: '--font-noto-arabic', preload: false });
export const notoTamil = Noto_Sans_Tamil({ weight: ['400','500','600','700','800','900'], subsets: ['tamil'], variable: '--font-noto-tamil', preload: false });
export const notoTelugu = Noto_Sans_Telugu({ weight: ['400','500','600','700','800','900'], subsets: ['telugu'], variable: '--font-noto-telugu', preload: false });

// Primary body font: tiny per-weight subset (generated by scripts/subset-fonts.ts,
// run on deploy) containing only the glyphs the site uses (~94% smaller). Preloaded
// so it lands before paint, killing the FOUT. `adjustFontFallback: false` keeps
// `.style.fontFamily` a single clean family name so layout.tsx can compose the
// fallback chain explicitly (subset -> full -> monospace -> sans-serif).
// NOTE: next/font requires `src` to be an explicitly written literal array — the two
// lists below are intentionally duplicated (subset vs full paths) for that reason.
export const juliaMonoSubset = localFont({
  src: [
    { path: './JuliaMono/subset/JuliaMono-Light.woff2',           weight: '300', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-LightItalic.woff2',     weight: '300', style: 'italic' },
    { path: './JuliaMono/subset/JuliaMono-Regular.woff2',         weight: '400', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-RegularLatin.woff2',    weight: '400', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-RegularItalic.woff2',   weight: '400', style: 'italic' },
    { path: './JuliaMono/subset/JuliaMono-Medium.woff2',          weight: '500', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-MediumItalic.woff2',    weight: '500', style: 'italic' },
    { path: './JuliaMono/subset/JuliaMono-SemiBold.woff2',        weight: '600', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-SemiBoldItalic.woff2',  weight: '600', style: 'italic' },
    { path: './JuliaMono/subset/JuliaMono-Bold.woff2',            weight: '700', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-BoldLatin.woff2',       weight: '700', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-BoldItalic.woff2',      weight: '700', style: 'italic' },
    { path: './JuliaMono/subset/JuliaMono-ExtraBold.woff2',       weight: '800', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-ExtraBoldItalic.woff2', weight: '800', style: 'italic' },
    { path: './JuliaMono/subset/JuliaMono-Black.woff2',           weight: '900', style: 'normal' },
    { path: './JuliaMono/subset/JuliaMono-BlackItalic.woff2',     weight: '900', style: 'italic' },
  ],
  display: 'swap',
  adjustFontFallback: false,
});

// Full font, NOT preloaded: only fetched per-glyph when the subset lacks a character
// (e.g. a new entry added via `pnpm sync` before the next deploy regenerates the
// subset). Same typeface as the subset, so swapping in introduces zero layout shift.
export const juliaMonoFull = localFont({
  src: [
    { path: './JuliaMono/JuliaMono-Light.woff2',           weight: '300', style: 'normal' },
    { path: './JuliaMono/JuliaMono-LightItalic.woff2',     weight: '300', style: 'italic' },
    { path: './JuliaMono/JuliaMono-Regular.woff2',         weight: '400', style: 'normal' },
    { path: './JuliaMono/JuliaMono-RegularLatin.woff2',    weight: '400', style: 'normal' },
    { path: './JuliaMono/JuliaMono-RegularItalic.woff2',   weight: '400', style: 'italic' },
    { path: './JuliaMono/JuliaMono-Medium.woff2',          weight: '500', style: 'normal' },
    { path: './JuliaMono/JuliaMono-MediumItalic.woff2',    weight: '500', style: 'italic' },
    { path: './JuliaMono/JuliaMono-SemiBold.woff2',        weight: '600', style: 'normal' },
    { path: './JuliaMono/JuliaMono-SemiBoldItalic.woff2',  weight: '600', style: 'italic' },
    { path: './JuliaMono/JuliaMono-Bold.woff2',            weight: '700', style: 'normal' },
    { path: './JuliaMono/JuliaMono-BoldLatin.woff2',       weight: '700', style: 'normal' },
    { path: './JuliaMono/JuliaMono-BoldItalic.woff2',      weight: '700', style: 'italic' },
    { path: './JuliaMono/JuliaMono-ExtraBold.woff2',       weight: '800', style: 'normal' },
    { path: './JuliaMono/JuliaMono-ExtraBoldItalic.woff2', weight: '800', style: 'italic' },
    { path: './JuliaMono/JuliaMono-Black.woff2',           weight: '900', style: 'normal' },
    { path: './JuliaMono/JuliaMono-BlackItalic.woff2',     weight: '900', style: 'italic' },
  ],
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
});

// Emoji icon font, applied via className. The icon set is hardcoded UI (not content),
// so its subset can never go stale — no full fallback layer needed here.
export const notoEmoji = localFont({
  src: [
    { path: './NotoEmoji/subset/noto-emoji-v62-emoji-300.woff2',     weight: '300', style: 'normal' },
    { path: './NotoEmoji/subset/noto-emoji-v62-emoji-regular.woff2', weight: '400', style: 'normal' },
    { path: './NotoEmoji/subset/noto-emoji-v62-emoji-500.woff2',     weight: '500', style: 'normal' },
    { path: './NotoEmoji/subset/noto-emoji-v62-emoji-600.woff2',     weight: '600', style: 'normal' },
    { path: './NotoEmoji/subset/noto-emoji-v62-emoji-700.woff2',     weight: '700', style: 'normal' },
  ],
  variable: '--font-noto-emoji',
  display: 'swap',
});